syms phi_p_j phi_d_j delta r d
f = sqrt((d*sin(phi_d_j)+r*cos(phi_d_j)*cos(delta)-r*cos(delta))^2 + ...
         (r*cos(delta)*sin(phi_p_j)*sin(phi_d_j)+r*cos(phi_p_j)*sin(delta)-d*sin(phi_p_j)*cos(phi_d_j)-r*sin(delta))^2 + ...
         (r*sin(phi_p_j)*sin(delta)-r*cos(delta)*cos(phi_p_j)*sin(phi_d_j)+d*cos(phi_p_j)*cos(phi_d_j)+d)^2);
f1=diff(f,phi_p_j);
f2=diff(f,phi_d_j);

dl_phi_p =(2*(r*cos(phi_p_j)*sin(delta) - d*cos(phi_d_j)*sin(phi_p_j) + ... 
           r*cos(delta)*sin(phi_d_j)*sin(phi_p_j))*(d + ... 
           d*cos(phi_d_j)*cos(phi_p_j) + r*sin(delta)*sin(phi_p_j) - ...
           r*cos(delta)*cos(phi_p_j)*sin(phi_d_j)) + ... 
           2*(d*cos(phi_d_j)*cos(phi_p_j) + r*sin(delta)*sin(phi_p_j) - ...
           r*cos(delta)*cos(phi_p_j)*sin(phi_d_j))*(r*sin(delta) + ...
           d*cos(phi_d_j)*sin(phi_p_j) - r*cos(phi_p_j)*sin(delta) - ... 
           r*cos(delta)*sin(phi_d_j)*sin(phi_p_j)))/(2*((d + ...
           d*cos(phi_d_j)*cos(phi_p_j) + r*sin(delta)*sin(phi_p_j) - ... 
           r*cos(delta)*cos(phi_p_j)*sin(phi_d_j))^2 + (d*sin(phi_d_j) - ... 
           r*cos(delta) + r*cos(delta)*cos(phi_d_j))^2 + (r*sin(delta) + ... 
           d*cos(phi_d_j)*sin(phi_p_j) - r*cos(phi_p_j)*sin(delta) - ... 
           r*cos(delta)*sin(phi_d_j)*sin(phi_p_j))^2)^(1/2));
       
dl_phi_d = -(2*(d*cos(phi_p_j)*sin(phi_d_j) + ...
             r*cos(delta)*cos(phi_d_j)*cos(phi_p_j))*...
             (d + d*cos(phi_d_j)*cos(phi_p_j) + ... 
             r*sin(delta)*sin(phi_p_j) - ...
             r*cos(delta)*cos(phi_p_j)*sin(phi_d_j)) - 2*(d*cos(phi_d_j) - ...
             r*cos(delta)*sin(phi_d_j))*(d*sin(phi_d_j) - r*cos(delta) + ...
             r*cos(delta)*cos(phi_d_j)) + 2*(d*sin(phi_d_j)*sin(phi_p_j) + ...
             r*cos(delta)*cos(phi_d_j)*sin(phi_p_j))*(r*sin(delta) + ...
             d*cos(phi_d_j)*sin(phi_p_j) - r*cos(phi_p_j)*sin(delta) - ...
             r*cos(delta)*sin(phi_d_j)*sin(phi_p_j)))/(2*((d + d*cos(phi_d_j)*cos(phi_p_j) + ... 
             r*sin(delta)*sin(phi_p_j) - ...
             r*cos(delta)*cos(phi_p_j)*sin(phi_d_j))^2 + (d*sin(phi_d_j) - ...
             r*cos(delta) + r*cos(delta)*cos(phi_d_j))^2 + (r*sin(delta) + ...
             d*cos(phi_d_j)*sin(phi_p_j) - r*cos(phi_p_j)*sin(delta) - ...
             r*cos(delta)*sin(phi_d_j)*sin(phi_p_j))^2)^(1/2));