function l = fcn(phi_d,phi_p,delta,d,r)
l = sqrt((d*sin(phi_d)+r*cos(phi_d)*cos(delta)-r*cos(delta))^2 + ...
         (r*cos(delta)*sin(phi_p)*sin(phi_d)+r*cos(phi_p)*sin(delta)-d*sin(phi_p)*cos(phi_d)-r*sin(delta))^2 + ...
         (r*sin(phi_p)*sin(delta)-r*cos(delta)*cos(phi_p)*sin(phi_d)+d*cos(phi_p)*cos(phi_d)+d)^2);

function [dl_phi_p,dl_phi_d] = fcn(phi_p,phi_d,delta,d,r)
dl_phi_p =(2*(r*cos(phi_p)*sin(delta) - d*cos(phi_d)*sin(phi_p) + ... 
           r*cos(delta)*sin(phi_d)*sin(phi_p))*(d + ... 
           d*cos(phi_d)*cos(phi_p) + r*sin(delta)*sin(phi_p) - ...
           r*cos(delta)*cos(phi_p)*sin(phi_d)) + ... 
           2*(d*cos(phi_d)*cos(phi_p) + r*sin(delta)*sin(phi_p) - ...
           r*cos(delta)*cos(phi_p)*sin(phi_d))*(r*sin(delta) + ...
           d*cos(phi_d)*sin(phi_p) - r*cos(phi_p)*sin(delta) - ... 
           r*cos(delta)*sin(phi_d)*sin(phi_p)))/(2*((d + ...
           d*cos(phi_d)*cos(phi_p) + r*sin(delta)*sin(phi_p) - ... 
           r*cos(delta)*cos(phi_p)*sin(phi_d))^2 + (d*sin(phi_d) - ... 
           r*cos(delta) + r*cos(delta)*cos(phi_d))^2 + (r*sin(delta) + ... 
           d*cos(phi_d)*sin(phi_p) - r*cos(phi_p)*sin(delta) - ... 
           r*cos(delta)*sin(phi_d)*sin(phi_p))^2)^(1/2));
       
dl_phi_d = -(2*(d*cos(phi_p)*sin(phi_d) + ...
             r*cos(delta)*cos(phi_d)*cos(phi_p))*...
             (d + d*cos(phi_d)*cos(phi_p) + ... 
             r*sin(delta)*sin(phi_p) - ...
             r*cos(delta)*cos(phi_p)*sin(phi_d)) - 2*(d*cos(phi_d) - ...
             r*cos(delta)*sin(phi_d))*(d*sin(phi_d) - r*cos(delta) + ...
             r*cos(delta)*cos(phi_d)) + 2*(d*sin(phi_d)*sin(phi_p) + ...
             r*cos(delta)*cos(phi_d)*sin(phi_p))*(r*sin(delta) + ...
             d*cos(phi_d)*sin(phi_p) - r*cos(phi_p)*sin(delta) - ...
             r*cos(delta)*sin(phi_d)*sin(phi_p)))/(2*((d + d*cos(phi_d)*cos(phi_p) + ... 
             r*sin(delta)*sin(phi_p) - ...
             r*cos(delta)*cos(phi_p)*sin(phi_d))^2 + (d*sin(phi_d) - ...
             r*cos(delta) + r*cos(delta)*cos(phi_d))^2 + (r*sin(delta) + ...
             d*cos(phi_d)*sin(phi_p) - r*cos(phi_p)*sin(delta) - ...
             r*cos(delta)*sin(phi_d)*sin(phi_p))^2)^(1/2));
